sudo: required

branches:
  only:
    - master
    - /201[7-9][0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker

language: node_js
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      node_js: "8"
      script: npm run test
    - stage: build and deploy container
      node_js: "8"
      script: ./build-docker-image.sh
