sudo: required

branches:
  only:
    - master
    - /201[7-9][0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker

language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules

script:
  - npm run test && ./build-docker-image.sh
