sudo: required

branches:
  only:
    - master
    - /201[7-9][0-1][0-9][0-3][0-9]/

services: docker

language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get -y install python3-pip python-dev
script:
  - npm run test
  - ./build-docker-image.sh
