name: Build docker image from pull request
on:
  pull_request:
    branches:
      - master
jobs:
  pr-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - name: Build push latest image as prod
        run: ./.github/workflows/scripts/build_pull_request.sh
